<?xml version="1.0"?>
<package format="3">
  <name>cartesian_planning</name>
  <version>0.1.2</version>
  <description>Tools for planning cartesian trajectories</description>
  <author email="arbogastaw@gmail.com">Alex Arbogast</author>
  <maintainer email="arbogastaw@gmail.com">Alex Arbogast</maintainer>
  <license>Apache2</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <exec_depend>cartesian_planner</exec_depend>
  <exec_depend>cartesian_planning_msgs</exec_depend>
  <exec_depend>cartesian_planning_server</exec_depend>
  <exec_depend>cartesian_planning_examples</exec_depend>

	<export>
		<build_type>ament_cmake</build_type>
	</export>
</package>
