<?xml version="1.0"?>
<package format="3">
  <name>cartesian_planner</name>
  <version>0.1.2</version>
  <description>The cartesian_planner package</description>
  <author email="arbogastaw@gmail.com">Alex Arbogast</author>
  <maintainer email="arbogastaw@gmail.com">Alex Arbogast</maintainer>
  <license>Apache2</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>urdf</depend>
  <depend>kdl_parser</depend>
  <depend>tf2_eigen</depend>
  <depend>trajectory_msgs</depend>
  <depend>cartesian_planning_msgs</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
