// Copyright 2023 Alex Arbogast
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#include <rclcpp/rclcpp.hpp>
#include <trajectory_msgs/msg/joint_trajectory.hpp>
#include <tf2_eigen/tf2_eigen.hpp>

#include <urdf/model.h>
#include <kdl/jntarray.hpp>
#include <kdl_parser/kdl_parser.hpp>

#include <cartesian_planner/cartesian_planner.h>
#include <cartesian_planning_msgs/srv/plan_cartesian_trajectory.hpp>

// auto-generated by generate_parameter_library
#include "cartesian_planning_server/cartesian_planning_server_parameters.hpp"

static const std::string NAME = "cartesian_planning_server";

namespace cartesian_planning_server
{

using PlanCartesianTrajectory =
    cartesian_planning_msgs::srv::PlanCartesianTrajectory;

using JointState = sensor_msgs::msg::JointState;

std::vector<double> joint_state_to_vector(const JointState& js,
                                          const std::vector<std::string>& names)
{
  std::unordered_map<std::string, size_t> name_to_index;
  for (size_t i = 0; i < js.name.size(); ++i)
  {
    name_to_index[js.name[i]] = i;
  }

  std::vector<double> result(names.size(), 0.0);
  for (size_t i = 0; i < names.size(); ++i)
  {
    size_t idx = name_to_index[names[i]];
    result[i] = js.position[idx];
  }
  return result;
}

class CartesianPlanningServer : public rclcpp::Node
{
public:
  CartesianPlanningServer() : Node(NAME)
  {
    param_listener_ =
        std::make_shared<cartesian_planning_server::ParamListener>(
            this->get_node_parameters_interface());

    if (!init())
    {
      RCLCPP_FATAL(this->get_logger(),
                   "Failed to initialize CartesianPlanningServer node");
      rclcpp::shutdown();
    }
  }

private:
  bool init()
  {
    const auto params = param_listener_->get_params();

    // Build kinematic chain
    KDL::Tree robot_tree;
    KDL::Chain robot_chain;
    urdf::Model robot_model;
    if (!robot_model.initString(params.robot_description))
    {
      RCLCPP_ERROR(this->get_logger(),
                   "Failed to initialize urdf model from 'robot_description'");
      return false;
    }
    if (!kdl_parser::treeFromUrdfModel(robot_model, robot_tree))
    {
      RCLCPP_FATAL(this->get_logger(),
                   "Failed to parse KDL tree from urdf model");
      return false;
    }
    if (!robot_tree.getChain(params.robot_base_link, params.end_effector_link,
                             robot_chain))
    {
      RCLCPP_FATAL(this->get_logger(),
                   "Failed to build kinematic chain from '%s' to '%s'. "
                   "Make sure these links exist in the URDF.",
                   params.robot_base_link.c_str(),
                   params.end_effector_link.c_str());
      return false;
    }

    // Initialize planner
    planner_ =
        std::make_unique<cartesian_planner::CartesianPlanner>(robot_chain);

    // Setup service
    plan_trajectory_service_ = this->create_service<PlanCartesianTrajectory>(
        NAME + "/plan_cartesian_trajectory",
        std::bind(&CartesianPlanningServer::planCartesianTrajectoryService,
                  this, std::placeholders::_1, std::placeholders::_2));
    return true;
  }

  void planCartesianTrajectoryService(
      const std::shared_ptr<PlanCartesianTrajectory::Request> req,
      std::shared_ptr<PlanCartesianTrajectory::Response> res)
  {
    const auto params = param_listener_->get_params();

    cartesian_planner::CartesianPlanningRequest request;
    request.position_threshold = params.position_threshold;
    request.max_sampling_step = params.max_sampling_step;
    request.max_step_iterations = params.max_step_iterations;
    request.damping = params.damping;
    request.max_linear_velocity = req->max_linear_velocity;
    request.max_angular_velocity = req->max_angular_velocity;
    request.scaling = static_cast<cartesian_planner::Order>(req->scaling);

    std::vector<double> q_start =
        joint_state_to_vector(req->start_state, params.joints);

    Eigen::Map<const Eigen::VectorXd> start_state(q_start.data(),
                                                  q_start.size());
    request.start_state = start_state;

    // Path
    Eigen::Isometry3d pose;
    for (const auto& point : req->path)
    {
      tf2::fromMsg(point, pose);
      request.path.push_back(pose);
    }

    // Plan
    cartesian_planner::CartesianPlanningResponse response;
    planner_->planCartesianTrajectory(request, response);

    if (!response.error_code)
    {
      RCLCPP_ERROR(this->get_logger(),
                   "Failed to plan Cartesian trajectory. "
                   "Planner returned with error code: %d",
                   response.error_code.val);
    }

    res->error_code = response.error_code;
    res->trajectory.points = response.joint_trajectory;
    res->trajectory.header.stamp = this->get_clock()->now();
    res->trajectory.joint_names = params.joints;
  }

  rclcpp::Service<PlanCartesianTrajectory>::SharedPtr plan_trajectory_service_;

  std::shared_ptr<cartesian_planning_server::ParamListener> param_listener_;
  std::unique_ptr<cartesian_planner::CartesianPlanner> planner_;
};

}  // namespace cartesian_planning_server

int main(int argc, char** argv)
{
  rclcpp::init(argc, argv);
  auto node =
      std::make_shared<cartesian_planning_server::CartesianPlanningServer>();
  rclcpp::spin(node);
  rclcpp::shutdown();
  return 0;
}
